version: "3.9"

services:
  app:
    build: ../..
    image: jsrpc:play
    container_name: jsrpc-app
    restart: unless-stopped
    environment:
      - BROWSER=chromium
      - HEADLESS=true
      - TARGET_URL=about:blank
      - JRPC_GROUP=default
      # TLS is terminated at nginx; keep app internal ws
      - TLS_ENABLE=false
    expose:
      - "12080"
    networks:
      - jsrpc_net

  nginx:
    image: nginx:1.26-alpine
    container_name: jsrpc-nginx
    restart: unless-stopped
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./conf.d:/etc/nginx/conf.d:ro
      # Mount your real certs here
      - ./certs:/etc/nginx/certs:ro
    networks:
      - jsrpc_net

networks:
  jsrpc_net:
    driver: bridge

